services:
  # The React Frontend service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - ai-orchestrator

  # The AI Orchestration Service (MCP Brain)
  ai-orchestrator:
    build: ./services/ai-orchestrator
    ports:
      - "8000:8000"
    volumes:
      - ./services/ai-orchestrator:/app
    # environment:
    #   - OPENAI_API_KEY=your_key_here # For future use

  # The Execution Agent
  execution-agent:
    build: ./services/execution-agent
    volumes:
      - ./services/execution-agent:/app
    command: tail -f /dev/null