services:
  # --- Frontend ---
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - ai-orchestrator

  # --- Backend Services ---
  ai-orchestrator:
    build: ./services/ai-orchestrator
    ports:
      - "8000:8000"
    volumes:
      - ./services/ai-orchestrator:/app
    env_file:
      - .env
    environment:
      # Add this environment variable for immediate logging
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq

  execution-orchestrator:
    build: ./services/execution-orchestrator
    volumes:
      - ./services/execution-orchestrator:/app
    env_file:
      - .env
    environment:
      # Add this environment variable for immediate logging
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
  
  execution-agent:
    build: ./services/execution-agent
    volumes:
      - ./services/execution-agent:/app
    shm_size: '2gb'
    env_file:
      - .env
    environment:
      # Add this environment variable for immediate logging
      - PYTHONUNBUFFERED=1
    depends_on:
      - execution-orchestrator

  # --- Infrastructure ---
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - "5672:5672"   # For services
      - "15672:15672" # For Management UI
    env_file:
      - .env

volumes:
  postgres_data: